{{- range $name, $config := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-{{ $.Values.global.namespace }}
  namespace: {{ $.Values.global.namespace }}
data:
  {{- range $key, $value := $config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
---
{{- end }}
