{{- range $name, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-{{ $.Values.global.namespace }}
  namespace: {{ $.Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $value := $secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}