apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/repo-owner/repo-name.git"
  username: "put in your usename"
  password: "personal access token"
