apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-services
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/repo-owner/repo-name.git
    targetRevision: targetBranch
    path: helm/chart/folder
    helm:
      valueFiles:
        - values.yaml
      parameters: []

  destination:
    server: https://kubernetes.default.svc
    namespace: targetNamespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
